<?php
$list = array(
'Adress'
,'Aktivitet'
,'Anläggning'
,'Anmälan'
,'Ansök senast'
,'Antagen'
,'Antal avdelningar'
,'Antal barn/elever'
,'Antal dagar'
,'Antal deltagare'
,'Antal lokaler'
,'Antal rum'
,'Antal utbildningsplatser'
,'Antalet lokaler'
,'Anvisningar'
,'Arrangemang'
,'Arrangemangsinfo'
,'Arrangör'
,'Artist'
,'Bassängstorlek'
,'Befattning'
,'Broschyr'
,'Butik'
,'Byggstart'
,'Caféer'
,'Dag'
,'Datum'
,'Datum för sammanträdet'
,'Demensplatser'
,'Dokumentets storlek'
,'Drivs av'
,'Efternamn'
,'Evenemang/Möte'
,'Fastighetsägare'
,'Filmnamn'
,'Format'
,'Frist'
,'Frist för brandskyddskontroll'
,'Frågor'
,'Föreläsningar'
,'Författare/projektledare'
,'Förnamn'
,'Gatukök/hamburgerbar'
,'Genre'
,'Granskning'
,'Har fritidshem'
,'Hemserviceinsatser'
,'Huvudman'
,'Information'
,'Inne-/utomhusbad'
,'Inriktning'
,'Insatser'
,'Kapacitet största lokal'
,'Kategori'
,'Klockslag'
,'Knutet till krögare'
,'Kontakt'
,'Kostnad'
,'Kurs'
,'Kursstart'
,'Kurstillfällen'
,'Kök'
,'Lokal/Evenemangsplats'
,'Lunchservering'
,'Lyssna på dagens kapitel'
,'Längd'
,'Lärare'
,'Matleverantör'
,'Max antal deltagare'
,'Maxkapacitet'
,'Mobiltelefon'
,'Målgrupp'
,'Namn'
,'Nivå'
,'Nummer'
,'Nämnd'
,'Närområde'
,'Nästa sammanträde'
,'Omfattning'
,'Omfång'
,'Område'
,'Ordförande'
,'Pedagogisk inriktning'
,'Plats'
,'Poäng'
,'Pris'
,'Programtitel'
,'Projekt'
,'Publiceringsdatum'
,'Publikation'
,'Publikkapacitet'
,'På anslagstavlan fr.o.m.'
,'På anslagstavlan t.o.m.'
,'Restaurang '
,'Samråd'
,'Scen'
,'Senaste granskning'
,'Smiley sedan'
,'Sign'
,'Sista ansökningsdag'
,'Skede'
,'Skolform'
,'Skolämne'
,'Sotningsfrist'
,'Språk'
,'Startar även'
,'Särskild målgrupp'
,'Sök senast'
,'Sökord'
,'Telefon'
,'Tid'
,'Tidsbegr. till'
,'Till fördjupning av översiktsplan för'
,'Tillträde'
,'Tilläggstjänster'
,'Titel'
,'Tjänst'
,'Typ'
,'Typ av dokument'
,'Utbildning'
,'Utbildningslängd / poäng'
,'Utförare'
,'Utomhus/Inomhus'
,'Utställning'
,'Val'
,'Verksamhet'
,'Vice ordförande'
,'Visas vecka'
,'Yrkeskategori'
,'Yta (kvm)'
,'Ytor och mått'
,'Ålder'
,'År'
,'Årskurs'
,'Ämne'
,'Ämne/område'
,'Öppettider'
,'Beräknas klart'
,'Ord'
,'Antagen av'
);
?> 
