---

- name: Install nginx
  apt:
    name=nginx
    state=latest

- name: Disable the default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
  - restart nginx

- name: Copy over nginx.conf
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Copy default.conf for nginx
  template:
    src=nginx.default.conf.j2
    dest=/etc/nginx/conf.d/default.conf
  notify:
    - restart nginx
